### ISSUE TITLE
可以取消最低api版本为28和需要"com.google.android.wearable"这个库的要求吗

### ISSUE THREAD

**Issue by huajiworld** [MicaProject/MicaBrowser#8]
自己的oppo watch 2也想用这个软件。系统是安卓8.0，不是wear os

**Comment by Malpl3naInk** [comment]
我在 Rel-AL 0.4 的基础上编译了一份, 不过由于我没有 oppo watch 2 , 所以我不清楚到底能不能运行
如果不能运行的话只能等到明天晚上借到了再说了
https://airportal.cn/114865/j3bcDgrpWY

**Comment by huajiworld** [comment]
> 我在 Rel-AL 0.4 的基础上编译了一份, 不过由于我没有 oppo watch 2 , 所以我不清楚到底能不能运行
> 如果不能运行的话只能等到明天晚上借到了再说了
> https://airportal.cn/114865/j3bcDgrpWY

OK了，感谢大佬
